
export type Review = {
  id: string;
  userName: string;
  rating: number;
  comment: string;
};

export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  rating: number;
  category: string;
  images: string[];
  reviews?: Review[];
  aiHint?: string;
};

export const categories = [
  "Smartphones & Accessories",
  "Phone Accessories",
  "Laptops",
  "Desktops",
  "Computer Accessories",
  "Audio & Headphones",
  "TVs & Entertainment",
  "Streaming Devices",
  "Gaming Consoles",
  "Cameras & Photography",
  "Camera Accessories",
  "Large Appliances",
  "Small Appliances",
  "Cookware",
  "Kitchen Tools",
  "Dinnerware",
  "Living Room Furniture",
  "Bedroom Furniture",
  "Dining Room",
  "Home Decor",
  "Tools & Hardware",
  "Lighting",
  "Storage & Organization",
  "Men's Casual Wear",
  "Men's Formal Wear",
  "Men's Activewear",
  "Women's Casual Wear",
  "Women's Formal Wear",
  "Women's Activewear",
  "Baby Clothing",
  "Kids Clothing",
  "Baby Gear",
  "Toys & Educational Games",
  "Athletic Shoes",
  "Casual Shoes",
  "Formal Shoes",
  "Hair Products",
  "Hair Tools",
  "Oral Care",
  "Grooming",
];

export const products: Product[] = [
  {
    id: "iphone-15-pro-max-256",
    name: "Apple iPhone 15 Pro Max (256GB)",
    description: "The ultimate iPhone. A17 Pro chip. A design forged in titanium. And the most powerful iPhone camera system ever.",
    price: 159900.00,
    rating: 4.9,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1695026543936-a21a5a73e535?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1695026543936-a21a5a73e535?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "iphone pro",
    reviews: [
      { id: "rev1", userName: "Aisha", rating: 5, comment: "Titanium feels amazing and the camera is mind-blowing." },
    ],
  },
  {
    id: "iphone-15-pro-max-512",
    name: "Apple iPhone 15 Pro Max (512GB)",
    description: "The ultimate iPhone with more storage for your photos, videos, and apps. A17 Pro chip and a design forged in titanium.",
    price: 179900.00,
    rating: 4.9,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1695026543936-a21a5a73e535?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1695026543936-a21a5a73e535?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "iphone pro"
  },
    {
    id: "iphone-15-pro-max-1tb",
    name: "Apple iPhone 15 Pro Max (1TB)",
    description: "The ultimate iPhone with a massive 1TB of storage for power users. A17 Pro chip and a design forged in titanium.",
    price: 199900.00,
    rating: 5.0,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1695026543936-a21a5a73e535?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1695026543936-a21a5a73e535?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "iphone pro"
  },
  {
    id: "samsung-s24-ultra-256",
    name: "Samsung Galaxy S24 Ultra (256GB)",
    description: "Galaxy AI is here. Search like never before, get real-time translation on a call, and edit your photos with AI.",
    price: 129999.00,
    rating: 4.8,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1707161384192-33729f2b858f?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1707161384192-33729f2b858f?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "samsung galaxy",
    reviews: [
      { id: "rev2", userName: "Rohan", rating: 5, comment: "The AI features are a game changer! The S Pen is better than ever." },
    ],
  },
  {
    id: "samsung-s24-ultra-512",
    name: "Samsung Galaxy S24 Ultra (512GB)",
    description: "Experience the power of Galaxy AI with expanded storage. The new standard of mobile AI is here.",
    price: 139999.00,
    rating: 4.8,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1707161384192-33729f2b858f?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1707161384192-33729f2b858f?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "samsung galaxy"
  },
  {
    id: "pixel-8-pro-128",
    name: "Google Pixel 8 Pro (128GB)",
    description: "The most advanced Pixel camera yet, with a pro-level main camera for better low-light photos, a sharper ultrawide lens, and a 5x telephoto lens.",
    price: 106999.00,
    rating: 4.7,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1700682236131-9f268e1c6b61?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1700682236131-9f268e1c6b61?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "google pixel",
  },
  {
    id: "pixel-8-pro-256",
    name: "Google Pixel 8 Pro (256GB)",
    description: "Google's smartest phone with more storage. Pro-level cameras, the powerful Google Tensor G3 chip, and an immersive 6.7-inch display.",
    price: 113999.00,
    rating: 4.7,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1700682236131-9f268e1c6b61?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1700682236131-9f268e1c6b61?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "google pixel"
  },
  {
    id: "oneplus-12-256",
    name: "OnePlus 12 (256GB)",
    description: "Shaped by time, the new OnePlus 12 is a masterful blend of luxury and performance. Powered by Snapdragon® 8 Gen 3 with a ProXDR Display.",
    price: 64999.00,
    rating: 4.6,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1598327105525-ce94429f4538?q=80&w=2804&auto=format&fit=crop", "https://images.unsplash.com/photo-1598327105525-ce94429f4538?q=80&w=2804&auto=format&fit=crop"],
    aiHint: "oneplus phone",
  },
  {
    id: "oneplus-12-512",
    name: "OnePlus 12 (512GB)",
    description: "Top-tier performance with maximum storage. A masterful blend of luxury and performance, powered by Snapdragon® 8 Gen 3 with a ProXDR Display.",
    price: 69999.00,
    rating: 4.7,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1598327105525-ce94429f4538?q=80&w=2804&auto=format&fit=crop", "https://images.unsplash.com/photo-1598327105525-ce94429f4538?q=80&w=2804&auto=format&fit=crop"],
    aiHint: "oneplus phone",
  },
  {
    id: "xiaomi-14-pro-256",
    name: "Xiaomi 14 Pro (256GB)",
    description: "Lens to legend. The Xiaomi 14 Pro features a Leica Summilux optical lens, delivering stunning clarity and performance in all lighting conditions.",
    price: 74999.00,
    rating: 4.5,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1621330397442-3c1370241c88?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1621330397442-3c1370241c88?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "xiaomi phone",
  },
  {
    id: "xiaomi-14-pro-512",
    name: "Xiaomi 14 Pro (512GB)",
    description: "Lens to legend with more space. The Xiaomi 14 Pro features a Leica Summilux optical lens and ample storage for all your high-resolution shots.",
    price: 81999.00,
    rating: 4.6,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1621330397442-3c1370241c88?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1621330397442-3c1370241c88?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "xiaomi phone",
  },
  {
    id: "iphone-14-128",
    name: "Apple iPhone 14 (128GB)",
    description: "A huge leap in battery life and a new, more advanced dual-camera system. All in a durable design with Ceramic Shield, tougher than any smartphone glass.",
    price: 69900.00,
    rating: 4.6,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1663492658892-2336688758b9?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1663492658892-2336688758b9?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "iphone 14",
  },
  {
    id: "iphone-14-256",
    name: "Apple iPhone 14 (256GB)",
    description: "More storage for your photos and 4K videos. A huge leap in battery life and a new, more advanced dual-camera system in a durable design.",
    price: 79900.00,
    rating: 4.7,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1663492658892-2336688758b9?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1663492658892-2336688758b9?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "iphone 14",
  },
  {
    id: "samsung-a55-128",
    name: "Samsung Galaxy A55 (128GB)",
    description: "Awesome is for everyone. The Galaxy A55 5G features a premium metal frame, an immersive 6.6-inch Super AMOLED display, and a versatile camera.",
    price: 39999.00,
    rating: 4.4,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?q=80&w=2787&auto=format&fit=crop", "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?q=80&w=2787&auto=format&fit=crop"],
    aiHint: "samsung phone",
  },
  {
    id: "samsung-a55-256",
    name: "Samsung Galaxy A55 (256GB)",
    description: "Awesome is for everyone, with more storage. The Galaxy A55 5G features a premium metal frame, an immersive display, and a versatile camera.",
    price: 42999.00,
    rating: 4.5,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?q=80&w=2787&auto=format&fit=crop", "https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?q=80&w=2787&auto=format&fit=crop"],
    aiHint: "samsung phone",
  },
  {
    id: "realme-gt-6-pro-256",
    name: "Realme GT 6 Pro (256GB)",
    description: "Flagship killer re-defined. Experience top-tier performance with the latest Snapdragon processor and a super-smooth 120Hz display.",
    price: 49999.00,
    rating: 4.5,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1631541999121-41a753d71893?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1631541999121-41a753d71893?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "realme phone"
  },
  {
    id: "realme-gt-6-pro-512",
    name: "Realme GT 6 Pro (512GB)",
    description: "Flagship killer with max storage. Experience top-tier performance with the latest Snapdragon processor and a super-smooth 120Hz display.",
    price: 54999.00,
    rating: 4.6,
    category: "Smartphones & Accessories",
    images: ["https://images.unsplash.com/photo-1631541999121-41a753d71893?q=80&w=2940&auto=format&fit=crop", "https://images.unsplash.com/photo-1631541999121-41a753d71893?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "realme phone"
  },
  {
    id: "magsafe-charger-apple",
    name: "Apple MagSafe Charger",
    description: "The MagSafe Charger makes wireless charging a snap. The perfectly aligned magnets attach to your iPhone to provide faster wireless charging up to 15W.",
    price: 4500.00,
    rating: 4.7,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1631144237195-2a6d7a42a0f5?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "wireless charger",
    reviews: [
      { id: "rev_acc1", userName: "Priya", rating: 5, comment: "So convenient! The magnetic connection is strong and it charges quickly." },
    ],
  },
  {
    id: "fast-charge-samsung",
    name: "Samsung 15W Wireless Charger",
    description: "Get the charge you need quickly, thanks to up to 15W of Fast Charging support. This boost of battery is compatible with USB PD and Adaptive Fast Charging travel adapters for an easy pick-me-up.",
    price: 3999.00,
    rating: 4.6,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1549643493-1b77874a77b8?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "samsung charger",
  },
  {
    id: "leather-case-iphone",
    name: "iPhone 15 Pro Leather Case",
    description: "Made from specially tanned and finished leather, the outside feels soft to the touch and develops a natural patina over time. It quickly snaps into place and fits snugly over your iPhone without adding bulk.",
    price: 5900.00,
    rating: 4.8,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1548246424-4b5331553a85?q=80&w=2787&auto=format&fit=crop"],
    aiHint: "leather case",
  },
  {
    id: "silicone-case-samsung",
    name: "Galaxy S24 Ultra Silicone Case",
    description: "The Silicone Case fits snugly around your phone. Its slim form factor doesn't add bulk, so although it helps prevent damage, it still fits easily in your pocket or bag.",
    price: 2499.00,
    rating: 4.5,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1614323992213-55d642afff20?q=80&w=2787&auto=format&fit=crop"],
    aiHint: "phone case",
  },
  {
    id: "tempered-glass-protector",
    name: "Tempered Glass Screen Protector",
    description: "High-quality tempered glass with 9H hardness. Provides maximum protection from scratches, scrapes, and bumps while maintaining perfect touch sensitivity.",
    price: 999.00,
    rating: 4.9,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1593344484962-796b16d8a39c?q=80&w=2787&auto=format&fit=crop"],
    aiHint: "screen protector",
  },
  {
    id: "power-bank-10000",
    name: "10000mAh Slim Power Bank",
    description: "One of the slimmest and lightest 10000mAh portable chargers on the market. Provides 2.25 charges for iPhone 12, 1.6 charges for Galaxy S20 and 1.2 charges for iPad mini 5.",
    price: 2199.00,
    rating: 4.7,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1588654294323-868c22744883?q=80&w=2787&auto=format&fit=crop"],
    aiHint: "power bank",
  },
  {
    id: "power-bank-20000",
    name: "20000mAh High-Capacity Power Bank",
    description: "With a massive 20,000mAh capacity, it provides more than 5 charges for iPhone XS, almost 5 full charges for Samsung Galaxy S10, and over 2 and a half charges for an iPad mini.",
    price: 3499.00,
    rating: 4.8,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1620596324393-510c4107e35b?q=80&w=2960&auto=format&fit=crop"],
    aiHint: "power bank",
  },
  {
    id: "usbc-lightning-cable",
    name: "Braided USB-C to Lightning Cable",
    description: "Durable and stylish braided nylon cable. MFi certified for flawless compatibility with all Lightning devices, ensuring the perfect charge every time.",
    price: 1599.00,
    rating: 4.6,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1614850523296-d8c1af93d400?q=80&w=2940&auto=format&fit=crop"],
    aiHint: "usb cable",
  },
  {
    id: "magnetic-car-mount",
    name: "Magnetic Car Phone Mount",
    description: "Extra strong magnetic car phone holder that securely holds your phone. Features a powerful magnet and a sturdy base that attaches to your dashboard or windshield.",
    price: 1899.00,
    rating: 4.5,
    category: "Phone Accessories",
    images: ["https://images.unsplash.com/photo-1596798033121-c4238e8a15cc?q=80&w=2835&auto=format&fit=crop"],
    aiHint: "car mount",
  },
  {
    id: 'macbook-air-m3-13',
    name: 'MacBook Air M3 (13-inch)',
    description: 'Strikingly thin and fast so you can work, play, or create anywhere. Powered by the M3 chip, it’s a supremely capable and portable laptop.',
    price: 114900.00,
    rating: 4.9,
    category: 'Laptops',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=2826&auto=format&fit=crop'],
    aiHint: 'macbook air',
  },
  {
    id: 'macbook-pro-m3-14',
    name: 'MacBook Pro M3 (14-inch)',
    description: 'The most advanced Mac laptop ever. With the M3 Pro or M3 Max chips, it delivers game-changing performance for the most demanding workflows.',
    price: 169900.00,
    rating: 4.9,
    category: 'Laptops',
    images: ['https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'macbook pro',
  },
  {
    id: 'dell-xps-13-plus',
    name: 'Dell XPS 13 Plus',
    description: 'Futuristic, minimalist design with a stunning OLED display. Powerful performance for all your creative projects and daily tasks.',
    price: 149990.00,
    rating: 4.7,
    category: 'Laptops',
    images: ['https://images.unsplash.com/photo-1606220857593-1d4b4556b6eb?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'dell laptop',
  },
  {
    id: 'hp-spectre-x360',
    name: 'HP Spectre x360',
    description: 'A convertible PC with a 360° hinge that adapts to you. Features a gem-cut design and a vibrant touchscreen for a premium experience.',
    price: 135000.00,
    rating: 4.6,
    category: 'Laptops',
    images: ['https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?q=80&w=2938&auto=format&fit=crop'],
    aiHint: 'hp laptop',
  },
  {
    id: 'imac-24-m3',
    name: 'Apple iMac 24" M3',
    description: 'You’ve never seen a computer like this before. With a stunningly thin design made possible by the Apple M3 chip. An immersive 24-inch 4.5K Retina display.',
    price: 134900.00,
    rating: 4.8,
    category: 'Desktops',
    images: ['https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'imac desktop',
  },
  {
    id: 'custom-gaming-pc',
    name: 'Custom Gaming PC',
    description: 'A high-performance gaming rig with the latest NVIDIA graphics, liquid cooling, and customizable RGB lighting. Built for extreme gaming.',
    price: 250000.00,
    rating: 4.9,
    category: 'Desktops',
    images: ['https://images.unsplash.com/photo-1598057076859-026891a27e0c?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'gaming pc',
  },
  {
    id: 'mac-studio',
    name: 'Mac Studio',
    description: 'An entirely new Mac desktop. With M2 Max and the new M2 Ultra, Mac Studio is a powerhouse that’s ready for any challenge.',
    price: 209900.00,
    rating: 4.9,
    category: 'Desktops',
    images: ['https://images.unsplash.com/photo-1652671561352-a6b107b36f87?q=80&w=2942&auto=format&fit=crop'],
    aiHint: 'mac studio',
  },
  {
    id: 'logitech-mx-keyboard',
    name: 'Logitech MX Mechanical Keyboard',
    description: 'A full-size mechanical keyboard with low-profile keys. Smart illumination and customizable keys for a fluid and efficient workflow.',
    price: 15495.00,
    rating: 4.8,
    category: 'Computer Accessories',
    images: ['https://images.unsplash.com/photo-1601445638532-3c6f6c3aa128?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'mechanical keyboard',
  },
  {
    id: 'logitech-mx-master-3s',
    name: 'Logitech MX Master 3S Mouse',
    description: 'An iconic mouse remastered. With an 8K DPI sensor and quiet clicks, it delivers ultimate precision and performance.',
    price: 10995.00,
    rating: 4.9,
    category: 'Computer Accessories',
    images: ['https://images.unsplash.com/photo-1615664739579-28c075a36f23?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'wireless mouse',
  },
  {
    id: 'dell-ultrasharp-4k-monitor',
    name: 'Dell UltraSharp 27" 4K Monitor',
    description: 'A 27-inch 4K UHD monitor with stunning color and clarity. Featuring ComfortView Plus to reduce harmful blue light emissions.',
    price: 59990.00,
    rating: 4.8,
    category: 'Computer Accessories',
    images: ['https://images.unsplash.com/photo-1527814223023-3a7956a25888?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'computer monitor',
  },
  {
    id: 'logitech-c920-webcam',
    name: 'Logitech C920 HD Pro Webcam',
    description: 'Full HD 1080p video calling and recording. Look your best in video calls with a glass lens and consistently clear image quality.',
    price: 7995.00,
    rating: 4.7,
    category: 'Computer Accessories',
    images: ['https://images.unsplash.com/photo-1616489953995-3929e7e324e9?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'webcam',
  },
  {
    id: 'samsung-t7-ssd',
    name: 'Samsung T7 Portable SSD 1TB',
    description: 'The new norm in external storage. Light, fast, and compact, the T7 delivers fast speeds with easy and reliable data storage.',
    price: 9499.00,
    rating: 4.9,
    category: 'Computer Accessories',
    images: ['https://images.unsplash.com/photo-1594434533434-9b973d47c433?q=80&w=2803&auto=format&fit=crop'],
    aiHint: 'external ssd',
  },
  {
    id: 'airpods-pro-2',
    name: 'Apple AirPods Pro (2nd Gen)',
    description: 'Re-engineered for even richer audio. Next-level Active Noise Cancellation and Adaptive Transparency reduce more external noise. Spatial Audio takes immersion to a remarkably personal level.',
    price: 24900.00,
    rating: 4.9,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1608043148419-9165761816b3?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'airpods pro',
  },
  {
    id: 'sony-wf1000xm5',
    name: 'Sony WF-1000XM5 Wireless Earbuds',
    description: 'The best noise canceling earbuds, period. Astonishing sound quality, and our best ever call quality. Everything in the WF-1000XM5 earbuds has been designed from the ground up.',
    price: 24990.00,
    rating: 4.8,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1627885793933-562d5774358f?q=80&w=2868&auto=format&fit=crop'],
    aiHint: 'sony earbuds',
  },
  {
    id: 'galaxy-buds2-pro',
    name: 'Samsung Galaxy Buds2 Pro',
    description: 'Studio-quality sound isn\'t just for the pros. Feel every note like you’re there with Galaxy Buds2 Pro. Get a next-level listening experience, from streaming your favorite playlist to playing your favorite game.',
    price: 15999.00,
    rating: 4.7,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1658498399516-a36c117d9348?q=80&w=2938&auto=format&fit=crop'],
    aiHint: 'samsung buds',
  },
  {
    id: 'bose-quietcomfort-earbuds',
    name: 'Bose QuietComfort Earbuds II',
    description: 'These next-generation wireless earbuds are engineered to for the best-in-class noise cancellation and immersive audio. It\'s a listening experience you won\'t find in any other wireless earbud.',
    price: 22900.00,
    rating: 4.8,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1620306148875-dd85553e1a8a?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'bose earbuds',
  },
  {
    id: 'sony-wh1000xm5',
    name: 'Sony WH-1000XM5 Headphones',
    description: 'Our best noise canceling just got better. See how these Sony headphones combine our best ever noise canceling technology with superlative sound for a truly remarkable listening experience.',
    price: 29990.00,
    rating: 4.9,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1651034942953-ce86743118a8?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'sony headphones',
  },
  {
    id: 'airpods-max',
    name: 'Apple AirPods Max',
    description: 'A perfect balance of exhilarating high-fidelity audio and the effortless magic of AirPods. The ultimate personal listening experience is here.',
    price: 59900.00,
    rating: 4.7,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1609342122563-a43ac8917a3a?q=80&w=2864&auto=format&fit=crop'],
    aiHint: 'apple headphones',
  },
  {
    id: 'beats-studio3-wireless',
    name: 'Beats Studio3 Wireless Headphones',
    description: 'Premium sound with fine-tuned acoustics and Pure ANC, the Beats Studio3 Wireless headphones deliver a premium listening experience. Soft over-ear cushions feature advanced venting and signature ergonomic pivoting for a custom, flexible fit.',
    price: 29900.00,
    rating: 4.6,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1545127398-14699f92334b?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'beats headphones',
  },
  {
    id: 'jbl-flip-6-speaker',
    name: 'JBL Flip 6 Bluetooth Speaker',
    description: 'Your adventure. Your soundtrack. The bold JBL Flip 6 delivers powerful JBL Original Pro Sound with exceptional clarity thanks to its 2-way speaker system.',
    price: 11999.00,
    rating: 4.8,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1678122421915-f9a37c385966?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'bluetooth speaker',
  },
  {
    id: 'amazon-echo-dot',
    name: 'Amazon Echo Dot (5th Gen)',
    description: 'Our most popular smart speaker with Alexa. The sleek, compact design delivers crisp vocals and balanced bass for full sound.',
    price: 4499.00,
    rating: 4.7,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1647491793041-355883a8bcee?q=80&w=2864&auto=format&fit=crop'],
    aiHint: 'smart speaker',
  },
  {
    id: 'sonos-arc-soundbar',
    name: 'Sonos Arc Soundbar',
    description: 'The premium smart soundbar for TV, movies, music, gaming, and more. Bring all your entertainment to life with the brilliantly realistic sound of Arc, featuring Dolby Atmos.',
    price: 89999.00,
    rating: 4.9,
    category: 'Audio & Headphones',
    images: ['https://images.unsplash.com/photo-1643198337289-3d441051525b?q=80&w=2938&auto=format&fit=crop'],
    aiHint: 'soundbar',
  },
  {
    id: 'samsung-qled-4k-55',
    name: 'Samsung QLED 4K TV (55")',
    description: 'Experience a billion shades of color with Quantum Dot technology. This 55-inch QLED TV delivers breathtaking color and contrast in 4K resolution.',
    price: 99990.00,
    rating: 4.8,
    category: 'TVs & Entertainment',
    images: ['https://images.unsplash.com/photo-1601944177324-f23675a2f5f1?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'samsung tv',
  },
  {
    id: 'lg-oled-4k-65',
    name: 'LG OLED 4K TV (65")',
    description: 'The ultimate viewing experience with self-lit pixels. Enjoy perfect black, infinite contrast, and over a billion colors on this stunning 65-inch OLED TV.',
    price: 219990.00,
    rating: 4.9,
    category: 'TVs & Entertainment',
    images: ['https://images.unsplash.com/photo-1628178613466-9b0c79524317?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'lg tv',
  },
  {
    id: 'sony-bravia-xr-65',
    name: 'Sony Bravia XR TV (65")',
    description: 'Next generation picture and sound with Cognitive Intelligence. See how we’ve revolutionized the TV experience with our Cognitive Processor XR™.',
    price: 239990.00,
    rating: 4.8,
    category: 'TVs & Entertainment',
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'sony tv',
  },
  {
    id: 'apple-tv-4k',
    name: 'Apple TV 4K',
    description: 'The future of television is here. Apple TV 4K lets you watch movies and shows in amazing 4K HDR and with immersive sound from Dolby Atmos.',
    price: 17900.00,
    rating: 4.9,
    category: 'Streaming Devices',
    images: ['https://images.unsplash.com/photo-1616486588914-23365887263b?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'apple tv',
  },
  {
    id: 'amazon-fire-stick',
    name: 'Amazon Fire TV Stick 4K',
    description: 'Cinematic experience, watch in vibrant 4K Ultra HD with support for Dolby Vision, HDR, and HDR10+. Launch and control content with the Alexa Voice Remote.',
    price: 4499.00,
    rating: 4.7,
    category: 'Streaming Devices',
    images: ['https://images.unsplash.com/photo-1624440312065-9f5b045f0d61?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'fire stick',
  },
  {
    id: 'google-chromecast',
    name: 'Google Chromecast with Google TV',
    description: 'Entertainment you love. In one place. Google TV organizes movies and TV shows from all of your favorite services into a single screen.',
    price: 4999.00,
    rating: 4.6,
    category: 'Streaming Devices',
    images: ['https://images.unsplash.com/photo-1619428239075-6351d3bdfd85?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'chromecast',
  },
  {
    id: 'playstation-5',
    name: 'PlayStation 5 Console',
    description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.',
    price: 49990.00,
    rating: 4.9,
    category: 'Gaming Consoles',
    images: ['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'playstation 5',
  },
  {
    id: 'xbox-series-x',
    name: 'Xbox Series X',
    description: 'The fastest, most powerful Xbox ever. Explore rich new worlds with 12 teraflops of raw graphic processing power, DirectX ray tracing, and a custom SSD.',
    price: 49990.00,
    rating: 4.8,
    category: 'Gaming Consoles',
    images: ['https://images.unsplash.com/photo-1627885793933-562d5774358f?q=80&w=2868&auto=format&fit=crop'],
    aiHint: 'xbox series',
  },
  {
    id: 'nintendo-switch-oled',
    name: 'Nintendo Switch OLED Model',
    description: 'Meet the newest member of the Nintendo Switch family! The new system features a vibrant 7-inch OLED screen, a wide adjustable stand, and 64 GB of internal storage.',
    price: 34999.00,
    rating: 4.8,
    category: 'Gaming Consoles',
    images: ['https://images.unsplash.com/photo-1654343210714-2ba1c48c4146?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'nintendo switch',
  },
  {
    id: 'canon-eos-r6-mk2',
    name: 'Canon EOS R6 Mark II',
    description: 'A hybrid powerhouse for photo and video. With a 24.2MP full-frame sensor, in-body image stabilization, and advanced subject tracking, it\'s built for creators.',
    price: 235995.00,
    rating: 4.9,
    category: 'Cameras & Photography',
    images: ['https://images.unsplash.com/photo-1512756290469-ec264b7fbf87?q=80&w=2853&auto=format&fit=crop'],
    aiHint: 'canon camera',
  },
  {
    id: 'sony-a7-iv',
    name: 'Sony Alpha a7 IV',
    description: 'Beyond basic. The α7 IV is our new standard for full-frame, seamlessly blending outstanding image quality for stills and movies with advanced connectivity.',
    price: 242990.00,
    rating: 4.9,
    category: 'Cameras & Photography',
    images: ['https://images.unsplash.com/photo-1596701062353-733e144a45a3?q=80&w=2824&auto=format&fit=crop'],
    aiHint: 'sony camera',
  },
  {
    id: 'fujifilm-xt5',
    name: 'Fujifilm X-T5',
    description: 'Portability and power. Featuring the new 40MP X-Trans CMOS 5 HR sensor, it delivers the highest image quality and resolution in the history of the X Series.',
    price: 164999.00,
    rating: 4.8,
    category: 'Cameras & Photography',
    images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=2864&auto=format&fit=crop'],
    aiHint: 'fujifilm camera',
  },
  {
    id: 'gopro-hero-12',
    name: 'GoPro HERO12 Black',
    description: 'Incredible image quality, even better HyperSmooth video stabilization and a huge boost in battery life come together in the latest and greatest GoPro.',
    price: 45000.00,
    rating: 4.7,
    category: 'Cameras & Photography',
    images: ['https://images.unsplash.com/photo-1520390138-945a36345439?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'gopro camera',
  },
  {
    id: 'dji-action-4',
    name: 'DJI Osmo Action 4',
    description: 'Capture the raw thrill of any moment with striking image quality and flexible performance. The Action 4’s 1/1.3-inch sensor lets you capture more.',
    price: 40990.00,
    rating: 4.7,
    category: 'Cameras & Photography',
    images: ['https://images.unsplash.com/photo-1623758419266-9964239859a2?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'dji camera',
  },
  {
    id: 'camera-lens-50mm',
    name: '50mm f/1.8 Prime Lens',
    description: 'A versatile and affordable prime lens, perfect for portraits and low-light photography. Its wide f/1.8 aperture creates beautiful background blur.',
    price: 12995.00,
    rating: 4.8,
    category: 'Camera Accessories',
    images: ['https://images.unsplash.com/photo-1599664223843-851543788796?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'camera lens',
  },
  {
    id: 'tripod-gimbal-combo',
    name: 'Travel Tripod & Gimbal Combo',
    description: 'The perfect kit for creators on the go. A lightweight, compact travel tripod paired with a 3-axis smartphone gimbal for smooth, cinematic shots.',
    price: 18999.00,
    rating: 4.6,
    category: 'Camera Accessories',
    images: ['https://images.unsplash.com/photo-1558503112-9c47087e35b0?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'camera tripod',
  },
  {
    id: 'camera-bag-dslr',
    name: 'DSLR & Mirrorless Camera Bag',
    description: 'A durable and weather-resistant camera backpack with customizable compartments to fit your camera body, lenses, and accessories safely.',
    price: 6499.00,
    rating: 4.7,
    category: 'Camera Accessories',
    images: ['https://images.unsplash.com/photo-1508212355531-0f748fc00a94?q=80&w=2942&auto=format&fit=crop'],
    aiHint: 'camera bag',
  },
  {
    id: 'sd-card-128gb',
    name: 'High-Speed 128GB SD Card',
    description: 'A V90-rated high-speed SD card, perfect for 4K video recording and high-resolution burst photography. Ensures you never miss a shot.',
    price: 5499.00,
    rating: 4.9,
    category: 'Camera Accessories',
    images: ['https://images.unsplash.com/photo-1581578330543-1e98835a643b?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'sd card',
  },
  {
    id: 'camera-battery-charger-kit',
    name: 'Dual Camera Battery Charger Kit',
    description: 'Never run out of power. This kit includes two replacement batteries and a dual-slot charger compatible with popular camera models.',
    price: 4999.00,
    rating: 4.8,
    category: 'Camera Accessories',
    images: ['https://images.unsplash.com/photo-1616428723933-787130616a69?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'battery charger',
  },
  {
    id: 'refrigerator-french-door',
    name: 'French Door Refrigerator',
    description: 'Spacious and stylish French door refrigerator with smart features, ample storage, and an ice maker. Perfect for modern kitchens.',
    price: 149990.00,
    rating: 4.8,
    category: 'Large Appliances',
    images: ['https://images.unsplash.com/photo-1601599589944-e3ab614138a2?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'refrigerator kitchen',
  },
  {
    id: 'built-in-dishwasher',
    name: 'Built-in Smart Dishwasher',
    description: 'Quiet and efficient built-in dishwasher with adjustable racks, multiple wash cycles, and stainless steel tub.',
    price: 59990.00,
    rating: 4.7,
    category: 'Large Appliances',
    images: ['https://images.unsplash.com/photo-1601131124237-7ac35a781b4f?q=80&w=2864&auto=format&fit=crop'],
    aiHint: 'dishwasher kitchen',
  },
  {
    id: 'over-range-microwave',
    name: 'Over-the-Range Microwave',
    description: 'Saves counter space while offering powerful cooking and ventilation. Features a sensor cook and a sleek, modern design.',
    price: 29990.00,
    rating: 4.6,
    category: 'Large Appliances',
    images: ['https://images.unsplash.com/photo-1604513367988-b99672658a3a?q=80&w=2882&auto=format&fit=crop'],
    aiHint: 'microwave oven',
  },
  {
    id: 'front-load-washer',
    name: 'Front-Load Washing Machine',
    description: 'High-efficiency front-load washer with steam cleaning technology, large capacity, and multiple wash cycles for all fabric types.',
    price: 74990.00,
    rating: 4.8,
    category: 'Large Appliances',
    images: ['https://images.unsplash.com/photo-1582735689369-7fe275442547?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'washing machine',
  },
  {
    id: 'air-fryer-ninja',
    name: 'Ninja Air Fryer',
    description: 'Enjoy guilt-free fried food. The Ninja Air Fryer crisps, roasts, reheats, and dehydrates for quick and easy meals.',
    price: 12999.00,
    rating: 4.9,
    category: 'Small Appliances',
    images: ['https://images.unsplash.com/photo-1633190108309-f83a4c17246c?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'air fryer',
  },
  {
    id: 'coffee-maker-nespresso',
    name: 'Nespresso Coffee Machine',
    description: 'Create barista-grade coffee beverages every time, thanks to Nespresso\'s one-touch system and premium coffee capsules.',
    price: 19990.00,
    rating: 4.8,
    category: 'Small Appliances',
    images: ['https://images.unsplash.com/photo-1565597933256-4809fd27a9e3?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'coffee machine',
  },
  {
    id: 'blender-vitamix',
    name: 'Vitamix High-Performance Blender',
    description: 'The blender trusted by professionals. Create smoothies, soups, and frozen desserts with one machine. A kitchen essential.',
    price: 49990.00,
    rating: 4.9,
    category: 'Small Appliances',
    images: ['https://images.unsplash.com/photo-1582787103173-021ba8353381?q=80&w=2938&auto=format&fit=crop'],
    aiHint: 'blender appliance',
  },
  {
    id: 'stand-mixer-kitchenaid',
    name: 'KitchenAid Stand Mixer',
    description: 'The iconic stand mixer. A powerful motor and a range of attachments make it the ultimate tool for bakers and creators.',
    price: 44990.00,
    rating: 4.9,
    category: 'Small Appliances',
    images: ['https://images.unsplash.com/photo-1643148636632-1f4868e42629?q=80&w=2864&auto=format&fit=crop'],
    aiHint: 'stand mixer',
  },
  {
    id: 'instant-pot-duo',
    name: 'Instant Pot Duo Pressure Cooker',
    description: 'The 7-in-1 multi-cooker that pressure cooks, slow cooks, makes yogurt, and more. A versatile appliance for busy kitchens.',
    price: 9999.00,
    rating: 4.8,
    category: 'Small Appliances',
    images: ['https://images.unsplash.com/photo-1631144237195-2a6d7a42a0f5?q=80&w=2940&auto=format&fit=crop'],
    aiHint: 'pressure cooker',
  },
  {
    id: 'electric-kettle',
    name: 'Electric Gooseneck Kettle',
    description: 'Perfect for pour-over coffee and tea. The gooseneck spout provides precise pouring control, and variable temperature settings ensure the perfect brew.',
    price: 6990.00,
    rating: 4.7,
    category: 'Small Appliances',
    images: ['https://images.unsplash.com/photo-1622329837775-9477e383b772?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'electric kettle',
  },
  {
    id: 'toaster-2-slice',
    name: 'Modern 2-Slice Toaster',
    description: 'A sleek and modern toaster with wide slots for bagels, variable browning control, and a high-lift lever for easy toast removal.',
    price: 4990.00,
    rating: 4.6,
    category: 'Small Appliances',
    images: ['https://images.unsplash.com/photo-1542977531-037305531a72?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'toaster appliance',
  },
  {
    id: 'cookware-set-nonstick',
    name: 'Non-stick Cookware Set (12-Piece)',
    description: 'A complete set of non-stick pots and pans for everyday cooking. Includes frying pans, saucepans, and stockpots with tempered glass lids.',
    price: 8999.00,
    rating: 4.7,
    category: 'Cookware',
    images: ['https://images.unsplash.com/photo-1583777972358-78227985065c?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'cookware set',
  },
  {
    id: 'cast-iron-skillet-12',
    name: '12-Inch Cast Iron Skillet',
    description: 'Pre-seasoned and ready to use. Perfect for searing, sautéing, baking, broiling, and frying. Unparalleled heat retention and even heating.',
    price: 3499.00,
    rating: 4.9,
    category: 'Cookware',
    images: ['https://images.unsplash.com/photo-1506464948625-26a1a11defa1?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'cast iron skillet',
  },
  {
    id: 'dutch-oven-5qt',
    name: '5-Quart Enameled Dutch Oven',
    description: 'A versatile and beautiful addition to any kitchen. Ideal for slow-cooking, braising, roasting, and baking. Vibrant enamel finish.',
    price: 7999.00,
    rating: 4.8,
    category: 'Cookware',
    images: ['https://images.unsplash.com/photo-1588602233638-3a4a18a93e3d?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'dutch oven',
  },
  {
    id: 'chefs-knife-8inch',
    name: '8-Inch Professional Chef\'s Knife',
    description: 'High-carbon stainless steel blade for precision and accuracy. An all-purpose knife perfect for chopping, mincing, slicing, and dicing.',
    price: 4999.00,
    rating: 4.9,
    category: 'Kitchen Tools',
    images: ['https://images.unsplash.com/photo-1620211534003-381a88a03423?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'chef knife',
  },
  {
    id: 'bamboo-cutting-board-set',
    name: 'Bamboo Cutting Board Set (3-Piece)',
    description: 'A set of three organic bamboo cutting boards in various sizes. Durable, eco-friendly, and gentle on knives. Perfect for all your chopping needs.',
    price: 2499.00,
    rating: 4.7,
    category: 'Kitchen Tools',
    images: ['https://images.unsplash.com/photo-1604470037893-33a38897a8a6?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'cutting board',
  },
  {
    id: 'mixing-bowl-set',
    name: 'Stainless Steel Mixing Bowls (Set of 5)',
    description: 'A set of 5 nesting mixing bowls with airtight lids. Perfect for mixing, baking, and food storage. Made from durable, high-quality stainless steel.',
    price: 3999.00,
    rating: 4.8,
    category: 'Kitchen Tools',
    images: ['https://images.unsplash.com/photo-1579824216958-403d9ce4b3b0?q=80&w=2788&auto=format&fit=crop'],
    aiHint: 'mixing bowls',
  },
  {
    id: 'dinnerware-set-16pc',
    name: '16-Piece Porcelain Dinnerware Set',
    description: 'Service for 4. Includes dinner plates, dessert plates, bowls, and mugs. A modern and elegant set for everyday use or special occasions.',
    price: 9999.00,
    rating: 4.8,
    category: 'Dinnerware',
    images: ['https://images.unsplash.com/photo-1621208948734-40c2c035b89a?q=80&w=2864&auto=format&fit=crop'],
    aiHint: 'dinnerware set',
  },
  {
    id: 'flatware-set-20pc',
    name: '20-Piece Silverware Flatware Set',
    description: 'Service for 4. Made of high-quality stainless steel, this set is durable and stylish. Includes dinner forks, salad forks, knives, spoons, and teaspoons.',
    price: 5999.00,
    rating: 4.7,
    category: 'Dinnerware',
    images: ['https://images.unsplash.com/photo-1558665425-4a29a0a01049?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'flatware set',
  },
  {
    id: 'wine-glasses-set-4',
    name: 'Red Wine Glasses (Set of 4)',
    description: 'Elegant and durable crystal wine glasses. The large bowl helps the wine\'s aromas and flavors to develop. Perfect for any wine lover.',
    price: 3499.00,
    rating: 4.9,
    category: 'Dinnerware',
    images: ['https://images.unsplash.com/photo-1549463515-b04043744655?q=80&w=2787&auto=format&fit=crop'],
    aiHint: 'wine glasses',
  },
  {
    id: "modern-sofa-sectional",
    name: "Modern Velvet Sofa Sectional",
    description: "A plush velvet sectional sofa with a modular design to fit any living space. Includes deep, comfortable seating and a chaise lounge.",
    price: 89999.00,
    rating: 4.7,
    category: "Living Room Furniture",
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=2940&auto=format&fit=crop'],
    aiHint: "modern sofa",
  },
  {
    id: "marble-coffee-table",
    name: "Round Marble Coffee Table",
    description: "An elegant coffee table featuring a genuine marble top and a sturdy metal base. Adds a touch of luxury to your living room.",
    price: 24999.00,
    rating: 4.8,
    category: "Living Room Furniture",
    images: ['https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "coffee table",
  },
  {
    id: "oak-tv-stand",
    name: "Minimalist Oak TV Stand",
    description: "A solid oak TV stand with clean lines and ample storage for media devices. Supports TVs up to 75 inches.",
    price: 19999.00,
    rating: 4.6,
    category: "Living Room Furniture",
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=2940&auto=format&fit=crop'],
    aiHint: "tv stand",
  },
  {
    id: "industrial-bookcase",
    name: "Industrial Metal & Wood Bookcase",
    description: "A five-tier bookcase combining a rustic wood finish with a sturdy metal frame. Perfect for displaying books and decor.",
    price: 15999.00,
    rating: 4.7,
    category: "Living Room Furniture",
    images: ['https://images.unsplash.com/photo-1594212699903-ec8a64e1f972?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "bookcase",
  },
  {
    id: "bohemian-area-rug",
    name: "Bohemian Style Area Rug",
    description: "A soft, plush area rug with a vibrant bohemian pattern. Adds warmth and style to any room. Size: 8' x 10'.",
    price: 12999.00,
    rating: 4.8,
    category: "Living Room Furniture",
    images: ['https://images.unsplash.com/photo-1619066045069-b598b3c698e1?q=80&w=2940&auto=format&fit=crop'],
    aiHint: "area rug",
  },
  {
    id: "upholstered-bed-frame-queen",
    name: "Upholstered Queen Bed Frame",
    description: "A stylish and modern upholstered bed frame with a tufted headboard and durable wooden slats. No box spring needed.",
    price: 34999.00,
    rating: 4.8,
    category: "Bedroom Furniture",
    images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16433d?q=80&w=2826&auto=format&fit=crop'],
    aiHint: "bed frame",
  },
  {
    id: "memory-foam-mattress-king",
    name: "King Memory Foam Mattress",
    description: "A 12-inch cooling gel memory foam mattress that provides pressure relief and a comfortable night's sleep. CertiPUR-US certified.",
    price: 59999.00,
    rating: 4.9,
    category: "Bedroom Furniture",
    images: ['https://images.unsplash.com/photo-1541648743533-5e7233a75f8f?q=80&w=2940&auto=format&fit=crop'],
    aiHint: "mattress bed",
  },
  {
    id: "mid-century-nightstand",
    name: "Mid-Century Modern Nightstand",
    description: "A solid wood nightstand with two drawers and tapered legs. Perfect for keeping your bedtime essentials organized.",
    price: 9999.00,
    rating: 4.7,
    category: "Bedroom Furniture",
    images: ['https://images.unsplash.com/photo-1594348624262-d2f8e12e8b09?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "nightstand bedroom",
  },
  {
    id: "6-drawer-dresser",
    name: "6-Drawer Double Dresser",
    description: "A spacious and sturdy dresser with six large drawers, perfect for storing clothes and linens. Features a clean, white finish.",
    price: 29999.00,
    rating: 4.6,
    category: "Bedroom Furniture",
    images: ['https://images.unsplash.com/photo-1616627781431-d85c884a7642?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "dresser furniture",
  },
  {
    id: "comforter-set-queen",
    name: "7-Piece Queen Comforter Set",
    description: "An all-season comforter set that includes a comforter, shams, and decorative pillows. Soft, hypoallergenic microfiber.",
    price: 7999.00,
    rating: 4.8,
    category: "Bedroom Furniture",
    images: ['https://images.unsplash.com/photo-1616627791419-158285521b36?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "bedding set",
  },
  {
    id: "dining-set-6-person",
    name: "6-Person Modern Dining Set",
    description: "A complete dining set with a rectangular table and six upholstered chairs. Perfect for family meals and entertaining guests.",
    price: 54999.00,
    rating: 4.7,
    category: "Dining Room",
    images: ['https://images.unsplash.com/photo-1517705008128-361805f42e86?q=80&w=2882&auto=format&fit=crop'],
    aiHint: "dining set",
  },
  {
    id: "bar-stools-set-2",
    name: "Adjustable Bar Stools (Set of 2)",
    description: "A pair of modern bar stools with a swivel design, adjustable height, and a comfortable backrest. Ideal for kitchen counters or home bars.",
    price: 11999.00,
    rating: 4.6,
    category: "Dining Room",
    images: ['https://images.unsplash.com/photo-1580480055273-2384a1412555?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "bar stools",
  },
  {
    id: "abstract-wall-art",
    name: "Abstract Canvas Wall Art",
    description: "A large, hand-painted abstract canvas that adds a bold statement to any room. Comes ready to hang.",
    price: 8999.00,
    rating: 4.8,
    category: "Home Decor",
    images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?q=80&w=2845&auto=format&fit=crop'],
    aiHint: "wall art",
  },
  {
    id: "round-wall-mirror",
    name: "Large Round Wall Mirror",
    description: "A 30-inch round mirror with a thin metal frame. Perfect for entryways, bathrooms, or as a decorative accent.",
    price: 7999.00,
    rating: 4.7,
    category: "Home Decor",
    images: ['https://images.unsplash.com/photo-1618221195720-dd6b41fae0a4?q=80&w=2864&auto=format&fit=crop'],
    aiHint: "wall mirror",
  },
  {
    id: "ceramic-vase-set",
    name: "Ceramic Vases (Set of 3)",
    description: "A set of three minimalist ceramic vases in different shapes and sizes. Ideal for displaying fresh flowers or pampas grass.",
    price: 3499.00,
    rating: 4.9,
    category: "Home Decor",
    images: ['https://images.unsplash.com/photo-1576026428059-99435a507857?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "ceramic vase",
  },
  {
    id: "snake-plant-pot",
    name: "Snake Plant in Ceramic Pot",
    description: "A low-maintenance snake plant in a stylish ceramic pot. A great air-purifying plant for any indoor space.",
    price: 2999.00,
    rating: 4.8,
    category: "Home Decor",
    images: ['https://images.unsplash.com/photo-1614555813333-e758a0a8f895?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "potted plant",
  },
  {
    id: "knit-throw-blanket",
    name: "Chunky Knit Throw Blanket",
    description: "A cozy and soft chunky knit blanket, perfect for snuggling on the couch. Adds texture and warmth to your home decor.",
    price: 4999.00,
    rating: 4.9,
    category: "Home Decor",
    images: ['https://images.unsplash.com/photo-1616627791419-158285521b36?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "throw blanket",
  },
  {
    id: "power-drill-cordless",
    name: "Cordless Power Drill Kit",
    description: "A versatile 20V cordless drill with two batteries, a charger, and a variety of drill bits. Perfect for all your DIY projects.",
    price: 7999.00,
    rating: 4.8,
    category: "Tools & Hardware",
    images: ['https://images.unsplash.com/photo-1590985223368-35688126b42b?q=80&w=2940&auto=format&fit=crop'],
    aiHint: "power drill",
  },
  {
    id: "hand-tool-set-120pc",
    name: "120-Piece Home Repair Tool Set",
    description: "A comprehensive tool set including a hammer, screwdrivers, wrenches, pliers, and more, all in a durable carrying case.",
    price: 5999.00,
    rating: 4.7,
    category: "Tools & Hardware",
    images: ['https://images.unsplash.com/photo-1541592106381-b5863c437731?q=80&w=2940&auto=format&fit=crop'],
    aiHint: "tool set",
  },
  {
    id: "led-bulbs-smart-4pack",
    name: "Smart Wi-Fi LED Bulbs (4-Pack)",
    description: "Dimmable, color-changing smart bulbs that work with Alexa and Google Assistant. No hub required.",
    price: 3999.00,
    rating: 4.6,
    category: "Lighting",
    images: ['https://images.unsplash.com/photo-1617041490226-c56430a6c671?q=80&w=2940&auto=format&fit=crop'],
    aiHint: "smart bulbs",
  },
  {
    id: "ceiling-fan-light-modern",
    name: "Modern Ceiling Fan with Light",
    description: "A 52-inch ceiling fan with a quiet, reversible motor and an integrated LED light kit. Includes a remote control for easy operation.",
    price: 14999.00,
    rating: 4.7,
    category: "Lighting",
    images: ['https://images.unsplash.com/photo-1615873968403-89e068629265?q=80&w=2832&auto=format&fit=crop'],
    aiHint: "ceiling fan",
  },
  {
    id: "shelving-unit-5-tier",
    name: "5-Tier Steel Shelving Unit",
    description: "A heavy-duty steel shelving unit, perfect for garages, basements, or workshops. Each shelf holds up to 800 lbs.",
    price: 9999.00,
    rating: 4.8,
    category: "Storage & Organization",
    images: ['https://images.unsplash.com/photo-1591129841117-3ad51fe5b715?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "storage shelves",
  },
  {
    id: "storage-bins-clear-6pack",
    name: "Clear Storage Bins (6-Pack)",
    description: "A set of six 66-quart clear plastic storage containers with latching lids. Ideal for organizing clothes, toys, and household items.",
    price: 4999.00,
    rating: 4.9,
    category: "Storage & Organization",
    images: ['https://images.unsplash.com/photo-1594820789947-2140b8a4593f?q=80&w=2787&auto=format&fit=crop'],
    aiHint: "storage bins",
  },
  {
    id: 'mens-tshirt-crewneck',
    name: "Classic Cotton Crewneck T-Shirt",
    description: "A soft, breathable 100% cotton t-shirt. A timeless wardrobe staple for everyday comfort.",
    price: 1499.00,
    rating: 4.7,
    category: "Men's Casual Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "men t-shirt",
  },
  {
    id: 'mens-jeans-slim',
    name: "Slim Fit Denim Jeans",
    description: "Modern slim fit jeans crafted from stretch denim for all-day comfort and style.",
    price: 3999.00,
    rating: 4.6,
    category: "Men's Casual Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "men jeans",
  },
  {
    id: 'mens-hoodie-fleece',
    name: "Fleece Pullover Hoodie",
    description: "A cozy pullover hoodie made from soft fleece, featuring a kangaroo pocket and drawstring hood.",
    price: 2999.00,
    rating: 4.8,
    category: "Men's Casual Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "men hoodie",
  },
  {
    id: 'mens-dress-shirt-white',
    name: "Wrinkle-Free Dress Shirt",
    description: "A crisp, white dress shirt made from a wrinkle-resistant cotton blend, perfect for the office or formal events.",
    price: 2499.00,
    rating: 4.7,
    category: "Men's Formal Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "men dress shirt",
  },
  {
    id: 'mens-suit-twopiece',
    name: "Two-Piece Wool Suit",
    description: "A classic two-piece suit tailored from 100% wool, featuring a modern fit for a sharp silhouette.",
    price: 14999.00,
    rating: 4.8,
    category: "Men's Formal Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "men suit",
  },
  {
    id: 'mens-running-shoes',
    name: "Men's Lightweight Running Shoes",
    description: "Engineered for performance with a breathable mesh upper and responsive cushioning for a comfortable run.",
    price: 6999.00,
    rating: 4.7,
    category: "Men's Activewear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "running shoes",
  },
  {
    id: 'mens-athletic-shorts',
    name: "Men's Athletic Performance Shorts",
    description: "Moisture-wicking shorts with a comfortable elastic waistband, perfect for workouts or running.",
    price: 1999.00,
    rating: 4.6,
    category: "Men's Activewear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "men shorts",
  },
  {
    id: 'womens-blouse-silk',
    name: "Silk-Blend Blouse",
    description: "An elegant and versatile blouse with a relaxed fit, perfect for work or a casual day out.",
    price: 3499.00,
    rating: 4.7,
    category: "Women's Casual Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "women blouse",
  },
  {
    id: 'womens-jeans-highwaist',
    name: "High-Waist Skinny Jeans",
    description: "Flattering high-waist jeans made from premium stretch denim that hugs your curves.",
    price: 4499.00,
    rating: 4.6,
    category: "Women's Casual Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "women jeans",
  },
  {
    id: 'womens-dress-floral',
    name: "Floral Midi Dress",
    description: "A beautiful floral print midi dress with a V-neck and a flowy silhouette, ideal for any occasion.",
    price: 5999.00,
    rating: 4.8,
    category: "Women's Casual Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "women dress",
  },
  {
    id: 'womens-blazer-tailored',
    name: "Tailored Business Blazer",
    description: "A chic, single-button blazer that adds a touch of sophistication to any outfit. Fully lined for comfort.",
    price: 7999.00,
    rating: 4.8,
    category: "Women's Formal Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "women blazer",
  },
  {
    id: 'womens-heels-classic',
    name: "Classic Pointed-Toe Heels",
    description: "Timeless and elegant pointed-toe pumps that are perfect for the office or a special event.",
    price: 4999.00,
    rating: 4.7,
    category: "Women's Formal Wear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "women heels",
  },
  {
    id: 'womens-yoga-pants',
    name: "High-Waist Yoga Leggings",
    description: "Buttery-soft and stretchy leggings that offer support and flexibility for yoga, gym, or everyday wear.",
    price: 3499.00,
    rating: 4.9,
    category: "Women's Activewear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "yoga pants",
  },
  {
    id: 'womens-sports-bra',
    name: "Medium-Support Sports Bra",
    description: "A comfortable and supportive sports bra with moisture-wicking fabric to keep you cool and dry.",
    price: 2499.00,
    rating: 4.7,
    category: "Women's Activewear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "sports bra",
  },
  {
    id: 'baby-onesies-5pack',
    name: "Organic Cotton Bodysuits (5-Pack)",
    description: "A set of five soft and breathable organic cotton onesies, perfect for your baby's delicate skin.",
    price: 2499.00,
    rating: 4.9,
    category: "Baby Clothing",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "baby onesies",
  },
  {
    id: 'baby-sleepers-3pack',
    name: "Zip-Up Fleece Sleepers (3-Pack)",
    description: "Keep your baby warm and cozy with these fleece footed pajamas featuring a convenient zip-up front.",
    price: 2999.00,
    rating: 4.8,
    category: "Baby Clothing",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "baby sleepers",
  },
  {
    id: 'kids-tshirt-graphic',
    name: "Kids Graphic T-Shirt",
    description: "A fun and comfortable t-shirt with a playful graphic print, made from 100% cotton.",
    price: 999.00,
    rating: 4.7,
    category: "Kids Clothing",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "kids t-shirt",
  },
  {
    id: 'kids-jeans-stretch',
    name: "Kids Stretch Denim Jeans",
    description: "Durable and comfortable jeans with an adjustable waistband for a perfect fit.",
    price: 1999.00,
    rating: 4.6,
    category: "Kids Clothing",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "kids jeans",
  },
  {
    id: 'baby-stroller-travel',
    name: "Lightweight Travel Stroller",
    description: "A compact and lightweight stroller that's easy to fold, perfect for families on the go.",
    price: 14999.00,
    rating: 4.8,
    category: "Baby Gear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "baby stroller",
  },
  {
    id: 'baby-car-seat-convertible',
    name: "All-in-One Convertible Car Seat",
    description: "A car seat that grows with your child, transitioning from rear-facing to forward-facing and then to a booster seat.",
    price: 24999.00,
    rating: 4.9,
    category: "Baby Gear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "car seat",
  },
  {
    id: 'baby-monitor-video',
    name: "Video Baby Monitor with Night Vision",
    description: "Keep an eye on your little one with a high-definition video monitor featuring two-way audio and infrared night vision.",
    price: 9999.00,
    rating: 4.7,
    category: "Baby Gear",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "baby monitor",
  },
  {
    id: 'building-blocks-100pc',
    name: "Wooden Building Blocks Set (100 Pieces)",
    description: "A classic set of 100 wooden blocks in various shapes and colors to inspire creativity and learning.",
    price: 2999.00,
    rating: 4.9,
    category: "Toys & Educational Games",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "building blocks",
  },
  {
    id: 'educational-tablet-kids',
    name: "Kids Learning Tablet",
    description: "An interactive tablet pre-loaded with educational games, e-books, and creative apps for kids ages 3-7.",
    price: 7999.00,
    rating: 4.6,
    category: "Toys & Educational Games",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "kids tablet",
  },
  {
    id: 'nike-running-shoes',
    name: "Nike Air Zoom Pegasus",
    description: "A responsive and neutral running shoe perfect for daily training. Features React foam and a Zoom Air unit.",
    price: 11895.00,
    rating: 4.8,
    category: "Athletic Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "nike running shoes",
  },
  {
    id: 'adidas-running-shoes',
    name: "Adidas Ultraboost Light",
    description: "Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever. Made in part with recycled materials.",
    price: 17999.00,
    rating: 4.7,
    category: "Athletic Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "adidas running shoes",
  },
  {
    id: 'basketball-shoes-jordan',
    name: "Air Jordan XXXVIII",
    description: "Built for the modern game, these shoes offer court mobility and responsiveness with low-to-the-ground cushioning.",
    price: 18395.00,
    rating: 4.9,
    category: "Athletic Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "basketball shoes",
  },
  {
    id: 'hiking-boots-waterproof',
    name: "Waterproof Hiking Boots",
    description: "Durable and waterproof hiking boots with excellent traction for tackling any trail in any weather.",
    price: 12999.00,
    rating: 4.7,
    category: "Athletic Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "hiking boots",
  },
  {
    id: 'sneakers-canvas-classic',
    name: "Classic Canvas Sneakers",
    description: "A timeless canvas sneaker that's versatile, comfortable, and perfect for everyday wear.",
    price: 4999.00,
    rating: 4.6,
    category: "Casual Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "canvas sneakers",
  },
  {
    id: 'loafers-leather-mens',
    name: "Men's Leather Loafers",
    description: "Slip into comfort and style with these genuine leather loafers, perfect for a smart-casual look.",
    price: 6999.00,
    rating: 4.8,
    category: "Casual Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "men loafers",
  },
  {
    id: 'sandals-leather-womens',
    name: "Women's Leather Sandals",
    description: "Comfortable and chic leather sandals with a cushioned footbed, ideal for summer days.",
    price: 3999.00,
    rating: 4.7,
    category: "Casual Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "women sandals",
  },
  {
    id: 'ankle-boots-chelsea',
    name: "Chelsea Ankle Boots",
    description: "A stylish and versatile Chelsea boot made from premium suede, featuring elastic side panels for an easy fit.",
    price: 8999.00,
    rating: 4.8,
    category: "Casual Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "chelsea boots",
  },
  {
    id: 'oxford-dress-shoes-mens',
    name: "Men's Oxford Dress Shoes",
    description: "Classic and sophisticated leather Oxfords, the perfect finishing touch for any formal attire.",
    price: 9999.00,
    rating: 4.9,
    category: "Formal Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "men dress shoes",
  },
  {
    id: 'pumps-high-heels-womens',
    name: "Women's High Heel Pumps",
    description: "Elegant and timeless high-heel pumps that provide both style and comfort for any formal occasion.",
    price: 7999.00,
    rating: 4.7,
    category: "Formal Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "women high heels",
  },
  {
    id: 'ballet-flats-womens',
    name: "Women's Leather Ballet Flats",
    description: "A comfortable and chic alternative to heels, these leather ballet flats are perfect for all-day wear.",
    price: 5999.00,
    rating: 4.8,
    category: "Formal Shoes",
    images: ['https://placehold.co/600x400.png'],
    aiHint: "women flats",
  },
  {
    id: 'shampoo-conditioner-set',
    name: 'Moisturizing Shampoo & Conditioner Set',
    description: 'A sulfate-free shampoo and conditioner set that hydrates and nourishes dry, damaged hair.',
    price: 2999.00,
    rating: 4.8,
    category: 'Hair Products',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'shampoo bottle',
  },
  {
    id: 'hair-styling-gel',
    name: 'Strong Hold Hair Styling Gel',
    description: 'Provides a long-lasting, strong hold without flaking. Perfect for creating a variety of hairstyles.',
    price: 999.00,
    rating: 4.6,
    category: 'Hair Products',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'hair gel',
  },
  {
    id: 'hair-mask-deep-conditioning',
    name: 'Deep Conditioning Hair Mask',
    description: 'An intensive hair treatment that repairs and restores dry, brittle hair, leaving it soft and silky.',
    price: 1999.00,
    rating: 4.9,
    category: 'Hair Products',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'hair mask',
  },
  {
    id: 'hair-dye-permanent-brown',
    name: 'Permanent Hair Color (Natural Brown)',
    description: 'A permanent hair dye that provides 100% gray coverage and rich, long-lasting color.',
    price: 1499.00,
    rating: 4.7,
    category: 'Hair Products',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'hair dye',
  },
  {
    id: 'hair-dryer-ionic',
    name: 'Professional Ionic Hair Dryer',
    description: 'A powerful 1875W hair dryer with ionic technology to reduce frizz and dry hair faster.',
    price: 4999.00,
    rating: 4.8,
    category: 'Hair Tools',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'hair dryer',
  },
  {
    id: 'flat-iron-ceramic',
    name: 'Ceramic Flat Iron Hair Straightener',
    description: 'A 1-inch ceramic flat iron that heats up quickly and glides smoothly for silky, straight hair.',
    price: 3999.00,
    rating: 4.7,
    category: 'Hair Tools',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'hair straightener',
  },
  {
    id: 'curling-iron-1-inch',
    name: '1-Inch Barrel Curling Iron',
    description: 'Create beautiful, long-lasting curls with this ceramic curling iron that provides even heat distribution.',
    price: 3499.00,
    rating: 4.6,
    category: 'Hair Tools',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'curling iron',
  },
  {
    id: 'hair-brush-detangling',
    name: 'Detangling Hair Brush',
    description: 'A gentle yet effective brush that glides through tangles without causing breakage or pain.',
    price: 1299.00,
    rating: 4.9,
    category: 'Hair Tools',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'hair brush',
  },
  {
    id: 'electric-toothbrush-oralb',
    name: 'Oral-B Electric Toothbrush',
    description: 'Removes 100% more plaque than a regular manual toothbrush. Features a pressure sensor and multiple cleaning modes.',
    price: 5999.00,
    rating: 4.9,
    category: 'Oral Care',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'electric toothbrush',
  },
  {
    id: 'toothpaste-whitening',
    name: 'Advanced Whitening Toothpaste',
    description: 'A fluoride toothpaste that not only whitens but also strengthens enamel and prevents cavities.',
    price: 499.00,
    rating: 4.7,
    category: 'Oral Care',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'toothpaste',
  },
  {
    id: 'teeth-whitening-strips',
    name: 'Teeth Whitening Strips (14 Treatments)',
    description: 'Visibly whitens teeth in just a few days. The no-slip grip means the strips stay put until you take them off.',
    price: 2499.00,
    rating: 4.6,
    category: 'Oral Care',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'whitening strips',
  },
  {
    id: 'electric-shaver-philips',
    name: 'Philips Norelco Electric Shaver',
    description: 'Provides a comfortable, close shave, wet or dry. The SkinProtect blades deliver a clean shave with fewer passes.',
    price: 8999.00,
    rating: 4.8,
    category: 'Grooming',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'electric shaver',
  },
  {
    id: 'beard-trimmer-kit',
    name: 'All-in-One Beard Trimmer Kit',
    description: 'A versatile grooming kit that includes a beard trimmer, hair clippers, and nose trimmer attachments.',
    price: 4999.00,
    rating: 4.7,
    category: 'Grooming',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'beard trimmer',
  },
  {
    id: 'cologne-mens-designer',
    name: 'Designer Men\'s Cologne',
    description: 'A sophisticated and long-lasting fragrance with notes of citrus, spice, and wood.',
    price: 7999.00,
    rating: 4.9,
    category: 'Grooming',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'cologne bottle',
  },
  {
    id: 'perfume-womens-floral',
    name: 'Floral Women\'s Perfume',
    description: 'A light and fresh floral perfume with notes of jasmine, rose, and peony. Perfect for everyday wear.',
    price: 8499.00,
    rating: 4.8,
    category: 'Grooming',
    images: ['https://placehold.co/600x400.png'],
    aiHint: 'perfume bottle',
  },
];
